>P1;query
sequence:query::::::::
MASPEQLELSGLIKSVHQRLRESAKHSDPETVWRKHIQDAPMLQNYAEAMHKLATQYWDR
TMDVTCKRSNSRIDWVAASCRTYFNGGLLNLFRDKDDKVMQAIDDAYRP-----------
THQPYCVEKIKMLDVGSCYNPFAAFADFEVTAIDIAPAQPDVWYCDFLEAEVKESIDRPQ
FLPEHHAIAAFPRNHYDAIVFSLLLEYLPTPDQRLRCCSKAYELLRPEGILLIITPDSRH
QGANARLMKNWRYTLAGIGFTRIKIEKLEHVTCMVFRRSLFAAVGKRWCAIHREAYMEPV
LNIPQDFNETSTSDERMDFVRTDADDDEIREAFSGLPFEDTVDSGFS*

>P1;7VKQ_clean
structureX:7VKQ_clean:73:A:401:A::::
------------------------------------------------------------
-----------RIKWAIDYITKYFFTEGIYLQKRQRERLL----ESYRAEGKLGEVQCRL
MEEP--PDRLHVLDVGSCFNPFSSAPHLEVTALDLCPATEDVLQADFLKVEVVPGIREPE
L--EEGSVRRLPASHYECVIFSLLLEYMPSAEQRLQCCLQAYDLLLPEGILVLITPDS--
-----HLMKNWRYSLARIGLLRVRFEKLPHISCMVFRKAISRELSQHWASIHREEGMCEE
IRIPQDDC---------------------------------------*
